version: "3.9"

networks:
  user-management:
    driver: bridge

services:
  postgres:
    image: postgres
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - user-management

  redis:
    image: redis
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    command: "--requirepass redis"
    volumes:
      - redis:/data
    networks:
      - user-management

  zookeeper:
    image: bitnami/zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    volumes:
      - zookeeper:/var/lib/zookeeper
    networks:
      - user-management

  kafka:
    image: bitnami/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
    volumes:
      - kafka:/var/lib/kafka
    networks:
      - user-management

volumes:
  postgres:
    external: false
  redis:
    external: false
  zookeeper:
    external: false
  kafka:
    external: false